FROM python:3.10-slim

WORKDIR /app

COPY requirements-web.txt .
RUN pip install --no-cache-dir -r requirements-web.txt

COPY app/ /app/

EXPOSE 8501

# Make sure the working directory is correct
WORKDIR /app

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
