version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./artifacts:/app/artifacts
      - ./local_storage:/app/local_storage
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/api
    networks:
      - healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./artifacts:/app/artifacts
      - ./local_storage:/app/local_storage
    depends_on:
      - ipfs
    environment:
      - IPFS_URL=http://ipfs:5001
      - BASE_RPC_URL=${BASE_RPC_URL:-https://api.developer.coinbase.com/rpc/v1/base-sepolia/TU79b5nxSoHEPVmNhElKsyBqt9CUbNTf}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-0x8Cbf9a04C9c7F329DCcaeabE90a424e8F9687aaA}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - MCL_LIB_PATH=/usr/local/lib/mcl
    networks:
      - healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    ports:
      - "4001:4001"  # IPFS swarm
      - "5001:5001"  # IPFS API
      - "8080:8080"  # IPFS Gateway
    volumes:
      - ipfs-data:/data/ipfs
      - ./local_storage:/export
    networks:
      - healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  healthcare-network:
    driver: bridge

volumes:
  ipfs-data:
