version: '3.8'

services:
  # Streamlit Web UI
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-web
    ports:
      - "8501:8501"  # Streamlit UI
    volumes:
      - ./app:/app/app
      - ./backend:/app/backend
      - ./pygroupsig:/app/pygroupsig
      - ./artifacts:/app/artifacts
      - ./local_storage:/app/local_storage
      - ./keys:/app/keys
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_URL=http://api:8000/api
      - PYTHONPATH=/app
      - PRIVATE_KEY=${PRIVATE_KEY:-91e5c2bed81b69f9176b6404710914e9bf36a6359122a2d1570116fc6322562e}
      - BASE_RPC_URL=${BASE_RPC_URL:-https://api.developer.coinbase.com/rpc/v1/base-sepolia/TU79b5nxSoHEPVmNhElKsyBqt9CUbNTf}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-0x8Cbf9a04C9c7F329DCcaeabE90a424e8F9687aaA}
      - DOCTOR_PRIVATE_KEY=${DOCTOR_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      - PATIENT_PRIVATE_KEY=${PATIENT_PRIVATE_KEY:-0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d}
      - HOSPITAL_PRIVATE_KEY=${HOSPITAL_PRIVATE_KEY:-0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a}
      - GROUP_MANAGER_PRIVATE_KEY=${GROUP_MANAGER_PRIVATE_KEY:-0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6}
      - REVOCATION_MANAGER_PRIVATE_KEY=${REVOCATION_MANAGER_PRIVATE_KEY:-0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a}
      - BUYER_PRIVATE_KEY=${BUYER_PRIVATE_KEY:-0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba}
    networks:
      - healthcare-network
    restart: unless-stopped
    command: streamlit run app/main.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501 || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-api
    ports:
      - "8000:8000"  # FastAPI
    volumes:
      - ./backend:/app/backend
      - ./pygroupsig:/app/pygroupsig
      - ./artifacts:/app/artifacts
      - ./local_storage:/app/local_storage
      - ./keys:/app/keys
    depends_on:
      ipfs:
        condition: service_healthy
    environment:
      - IPFS_URL=http://ipfs:5001
      - BASE_RPC_URL=${BASE_RPC_URL:-https://api.developer.coinbase.com/rpc/v1/base-sepolia/TU79b5nxSoHEPVmNhElKsyBqt9CUbNTf}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-0x8Cbf9a04C9c7F329DCcaeabE90a424e8F9687aaA}
      - PRIVATE_KEY=${PRIVATE_KEY:-91e5c2bed81b69f9176b6404710914e9bf36a6359122a2d1570116fc6322562e}
      - MCL_LIB_PATH=/usr/local/lib/mcl
      - PYTHONPATH=/app
      - DOCTOR_PRIVATE_KEY=${DOCTOR_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      - PATIENT_PRIVATE_KEY=${PATIENT_PRIVATE_KEY:-0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d}
      - HOSPITAL_PRIVATE_KEY=${HOSPITAL_PRIVATE_KEY:-0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a}
      - GROUP_MANAGER_PRIVATE_KEY=${GROUP_MANAGER_PRIVATE_KEY:-0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6}
      - REVOCATION_MANAGER_PRIVATE_KEY=${REVOCATION_MANAGER_PRIVATE_KEY:-0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a}
      - BUYER_PRIVATE_KEY=${BUYER_PRIVATE_KEY:-0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba}
    networks:
      - healthcare-network
    restart: unless-stopped
    command: uvicorn backend.api:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # IPFS Node
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    ports:
      - "4001:4001"  # IPFS swarm
      - "5001:5001"  # IPFS API
      - "8080:8080"  # IPFS Gateway
    volumes:
      - ipfs-data:/data/ipfs
      - ./local_storage:/export
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    networks:
      - healthcare-network
    restart: unless-stopped
    # Use the default entrypoint and command
    healthcheck:
      test: ["CMD-SHELL", "ipfs id || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  healthcare-network:
    driver: bridge

volumes:
  ipfs-data:
    driver: local
