version: '3.8'

services:
  healthcare-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-web
    hostname: web
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./backend:/app/backend
      - ./pygroupsig:/app/pygroupsig
      - ./artifacts:/app/artifacts
      - ./local_storage:/app/local_storage
    depends_on:
      - healthcare-api
    environment:
      - API_URL=http://healthcare-api:8000/api
      - PYTHONPATH=/app
      - PRIVATE_KEY=${PRIVATE_KEY:-91e5c2bed81b69f9176b6404710914e9bf36a6359122a2d1570116fc6322562e}
      - BASE_RPC_URL=${BASE_RPC_URL:-https://api.developer.coinbase.com/rpc/v1/base-sepolia/TU79b5nxSoHEPVmNhElKsyBqt9CUbNTf}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-0x8Cbf9a04C9c7F329DCcaeabE90a424e8F9687aaA}
    networks:
      - healthcare-network
    restart: unless-stopped
    command: streamlit run app/main.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

  healthcare-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-api
    hostname: api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./pygroupsig:/app/pygroupsig
      - ./artifacts:/app/artifacts
      - ./local_storage:/app/local_storage
      - ./test_contract.py:/app/test_contract.py
      - ./keys:/app/keys
    depends_on:
      - ipfs
    environment:
      - IPFS_URL=/dns4/ipfs/tcp/5001
      - BASE_RPC_URL=${BASE_RPC_URL:-https://api.developer.coinbase.com/rpc/v1/base-sepolia/TU79b5nxSoHEPVmNhElKsyBqt9CUbNTf}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-0x8Cbf9a04C9c7F329DCcaeabE90a424e8F9687aaA}
      - PRIVATE_KEY=${PRIVATE_KEY:-91e5c2bed81b69f9176b6404710914e9bf36a6359122a2d1570116fc6322562e}
      - MCL_LIB_PATH=/usr/local/lib/mcl
      - PYTHONPATH=/app
    networks:
      - healthcare-network
    restart: unless-stopped
    command: bash -c "python /app/check_keys.py && uvicorn backend.api:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    ports:
      - "4001:4001"  # IPFS swarm
      - "5001:5001"  # IPFS API
      - "8080:8080"  # IPFS Gateway
    volumes:
      - ipfs-data:/data/ipfs
      - ./local_storage:/export
    networks:
      - healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  healthcare-network:
    driver: bridge

volumes:
  ipfs-data:
