[tool.mypy]
cache_dir = "/dev/null"
exclude = ["tests/"]
#show_column_numbers = true
#show_error_codes = true
#allow_redefinition = true
#disallow_untyped_defs = true
#disallow_incomplete_defs = true
#no_implicit_optional = true
#warn_redundant_casts = true
#warn_unused_configs = true
#warn_unused_ignores = true
#warn_unreachable = true

[tool.ruff]
line-length = 80

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["E741"]

[tool.ruff.lint.pycodestyle]
max-line-length = 80

