from abc import ABCMeta, abstractmethod


class SchemeInterface(metaclass=ABCMeta):
    @abstractmethod
    def setup(self) -> None: ...
    @abstractmethod
    def join_mem(self, phase: int, message: dict[str, str] | None = None) -> dict[str, str]: ...
    @abstractmethod
    def join_mgr(self, phase: int, message: dict[str, str] | None = None) -> dict[str, str]: ...
    @abstractmethod
    def sign(self, message: str | bytes) -> dict[str, str]: ...
    @abstractmethod
    def verify(self, message: str | bytes, signature: str) -> dict[str, str]: ...

class KeyInterface(metaclass=ABCMeta): ...

class SignatureInterface(metaclass=ABCMeta): ...
