from typing import Type, TypeAlias, TypeVar

from pygroupsig.utils.mcl import Fr as Fr

T = TypeVar("T")

class ReprMixin: ...

class InfoMixin:
    def info(self) -> tuple[tuple[str], list[str]]: ...

class B64Mixin:
    def to_b64(self) -> str: ...
    def set_b64(self, s: str | bytes) -> None: ...
    @classmethod
    def from_b64(cls: Type[T], s: str | bytes) -> T: ...

class JoinMixin:
    def join_seq(self) -> int: ...
    def join_start(self) -> int: ...

class ContainerDict:
    def to_b64(self) -> str: ...
    def set_b64(self, s: str | bytes) -> None: ...
    @classmethod
    def from_b64(cls: Type[T], s: str | bytes) -> T: ...

GML: TypeAlias = ContainerDict
CRL: TypeAlias = ContainerDict
